FROM jenkins/jnlp-slave:3.26-1-alpine
LABEL maintainer="vAndrucha77"
LABEL versions="DockerClient17.10.0 Notary0.4.3"

USER root

RUN apk add --upgrade --no-cache \
    ca-certificates \
    openssh \
    openssh-server \
    git \
    bash \
    sudo \
    wget \
    curl && \
    rm -rf /var/cache/apk/*



# Copy Accross UCP Certs
COPY ucp-bundle-ci-pipeline.zip /home/jenkins/
RUN (unzip /home/jenkins/ucp-bundle-ci-pipeline.zip -d /home/jenkins/ && \
    cp /home/jenkins/ca.pem /usr/local/share/ca-certificates/ca.pem && \
    curl -k https://dtr.andreas.dtcntr.net/ca -o /usr/local/share/ca-certificates/dtr.andreas.dtcntr.net.crt && \
    update-ca-certificates)

# Install the Docker Client
RUN (wget -O /tmp/docker-static.tgz "https://download.docker.com/linux/static/edge/x86_64/docker-17.10.0-ce.tgz" &&\
  cd /tmp &&\
  tar -vxzf docker-static.tgz &&\
  mv /tmp/docker/docker /usr/local/bin/docker &&\
  chmod +x /usr/local/bin/docker &&\
  rm -rf /tmp/docker /tmp/docker-static.tgz)

# install notary
RUN (wget -O /usr/local/bin/notary "https://github.com/docker/notary/releases/download/v0.4.3/notary-Linux-amd64" &&\
  chmod +x /usr/local/bin/notary)

#copy notary data
COPY docker/ /home/jenkins/.docker/ 

# Add user jenkins to the image
RUN (addgroup jenkins ping && \
    echo "jenkins:jenkins" | chpasswd && \
    chown -R jenkins:jenkins /home/jenkins/* && \
    chown -R jenkins:jenkins /home/jenkins/.docker/ && \
    chmod 600 /home/jenkins/.docker/tls/dtr.andreas.dtcntr.net/ca.crt)
    
# Expose SSH
EXPOSE 22

USER jenkins