version: "3.3"

services:
  jenkins:
      image: dtr.andreas.dtcntr.net/docker-cemea/jenkins:2.88-alpine
      deploy:
          mode: replicated
          replicas: 1
          placement:
              constraints:
                  - 'node.platform.os == linux'
                  - 'node.hostname == wn01.andreas.dtcntr.net'
#      labels:
#                com.docker.lb.hosts: jenkins.swarm.andreas.dtcntr.net
#                com.docker.lb.network: cicd
#                com.docker.lb.port: 8080  
      networks:
          - cicd
      ports:
        - 30000:8080
        - 50000:50000
      volumes:
          - jenkins:/var/jenkins_home
volumes:
    jenkins:

networks:
      cicd:
       driver: overlay
